// src/app/layout.js
import "./globals.css"; // Imports global styles (includes Raleway font setting)
import LayoutWrapper from "../../src/app/components/LayoutWrapper";

// Metadata for the page
export const metadata = {
  title: "Create Next App", // Sets page title
  description: "Generated by create next app", // Sets page description
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {" "}
      {/* Sets language to English for accessibility */}
      <head>
        {/* You can include other meta tags or links here if needed */}
      </head>
      <body className="antialiased">
        {/* antialiased: Smooths font edges for improved readability */}
        <LayoutWrapper>
          {children} {/* Renders all page content inside the layout */}
        </LayoutWrapper>
      </body>
    </html>
  );
}
